name: Deploy Extension
on:
  release:
    types: [published]
jobs:
  public-to-open-vsx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run package
      - name: Public extension
        run: npm run publish:open-vsx -- -p ${{ secrets.OVSX_ACCESS_TOKEN }}
  public-to-vsce-marketplace:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run package
      - name: Public extension
        run: npm run publish:vsce-marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_MARKETPLACE_ACCESS_TOKEN }}
